// <auto-generated />
using System;
using ExamenEximicion.Libreria.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegistroInaiso.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ExamenEximicion.RegistroInaiso.Models.App", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("ExamenEximicion.RegistroInaiso.Models.Reservation", b =>
                {
                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("App_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("App_name")
                        .HasColumnType("TEXT");

                    b.Property<long>("User_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User_name")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservedAt");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ExamenEximicion.RegistroInaiso.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
